obj-m += tas2101.o
obj-m += si2168.o
obj-m += si2183.o
obj-m += mxl603.o
obj-m += mtv23x.o
obj-m += m88rs6060.o
obj-m += gx1503.o
obj-m += tas2971.o
obj-m += mxl58x.o
obj-m += si2157.o
obj-m += av201x.o
obj-m += stv091x.o
obj-m += stv6120.o
obj-m += mn88436.o
obj-m += rda5816.o
obj-m += gx1133.o
obj-m += cxd2878.o
obj-m += r850.o

stid135-objs := stid135/stid135-fe.o stid135/chip.o stid135/stfe_utilities.o stid135/oxford_anafe_func.o
stid135-objs += stid135/stid135_init.o stid135/stid135_drv.o
ccflags-y += -DHOST_PC
obj-m += stid135.o

tbsecp3-objs := tbsecp3-core.o tbsecp3-cards.o tbsecp3-i2c.o tbsecp3-dma.o tbsecp3-dvb.o tbsecp3-ca.o
tbsecp3-objs += tbsecp3-asi.o tbsecp3-ci.o
obj-m += tbsecp3.o

tbs_pcie-mod-objs += tbsmod/tbsmod.o
obj-m += tbs_pcie-mod.o

tbs_pcie-ci-objs += tbsci/tbsci.o
obj-m += tbs_pcie-ci.o

tns_priv-objs := tbs_priv.o
obj-m += tbs_priv.o

ccflags-y += -DCONFIG_MEDIA_CONTROLLER=1
ccflags-y += -DCONFIG_MEDIA_CONTROLLER_DVB=1

ccflags-y += -Idrivers/media/tuners
ccflags-y += -Idrivers/media/dvb-core
ccflags-y += -Idrivers/media/dvb-frontends
ccflags-y += -I$(M)/stid135
ccflags-y += -I$(M)

